// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var ReactNative = require("react-native");
var Text$BsReactNativeWeb = require("./text.js");
var View$BsReactNativeWeb = require("./view.js");
var Image$BsReactNativeWeb = require("./image.js");
var FlatList$BsReactNativeWeb = require("./flatList.js");
var AnimatedRe$BsReactNativeWeb = require("../animatedRe.js");
var ScrollView$BsReactNativeWeb = require("./scrollView.js");

var view = ReactNative.Animated.View;

var View = View$BsReactNativeWeb.CreateComponent(/* module */[/* view */view]);

var view$1 = ReactNative.Animated.Image;

var Image = Image$BsReactNativeWeb.CreateComponent(/* module */[/* view */view$1]);

var view$2 = AnimatedRe$BsReactNativeWeb.createAnimatedComponent(ReactNative.FlatList);

var FlatList = FlatList$BsReactNativeWeb.CreateComponent(/* module */[/* view */view$2]);

var view$3 = ReactNative.Animated.Text;

var Text = Text$BsReactNativeWeb.CreateComponent(/* module */[/* view */view$3]);

function onScrollUpdater(x, y, $staropt$star, _) {
  var $$native = $staropt$star !== undefined ? $staropt$star : false;
  return AnimatedRe$BsReactNativeWeb.$$event(/* array */[{
                nativeEvent: {
                  contentOffset: {
                    x: Js_undefined.fromOption(x),
                    y: Js_undefined.fromOption(y)
                  }
                }
              }], {
              useNativeDriver: $$native
            });
}

var view$4 = ReactNative.Animated.ScrollView;

var include = ScrollView$BsReactNativeWeb.CreateComponent(/* module */[/* view */view$4]);

var ScrollView_001 = /* scrollTo */include[0];

var ScrollView_002 = /* scrollToEnd */include[1];

var ScrollView_003 = /* make */include[2];

var ScrollView = /* module */[
  /* onScrollUpdater */onScrollUpdater,
  ScrollView_001,
  ScrollView_002,
  ScrollView_003
];

exports.View = View;
exports.Image = Image;
exports.Text = Text;
exports.FlatList = FlatList;
exports.ScrollView = ScrollView;
/* View Not a pure module */
