// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var AnimatedRe$BsReactNativeWeb = require("./animatedRe.js");

var Animation = AnimatedRe$BsReactNativeWeb.Animation;

var Interpolation = AnimatedRe$BsReactNativeWeb.Interpolation;

var Value = AnimatedRe$BsReactNativeWeb.Value;

var ValueXY = AnimatedRe$BsReactNativeWeb.ValueXY;

var $$event = AnimatedRe$BsReactNativeWeb.$$event;

var delay = AnimatedRe$BsReactNativeWeb.delay;

var sequence = AnimatedRe$BsReactNativeWeb.sequence;

var parallel = AnimatedRe$BsReactNativeWeb.parallel;

var stagger = AnimatedRe$BsReactNativeWeb.stagger;

var loop = AnimatedRe$BsReactNativeWeb.loop;

var createAnimatedComponent = AnimatedRe$BsReactNativeWeb.createAnimatedComponent;

var timing = AnimatedRe$BsReactNativeWeb.timing;

var spring = AnimatedRe$BsReactNativeWeb.spring;

var decay = AnimatedRe$BsReactNativeWeb.decay;

var stop = AnimatedRe$BsReactNativeWeb.stop;

var start = AnimatedRe$BsReactNativeWeb.start;

var reset = AnimatedRe$BsReactNativeWeb.reset;

var Text = 0;

var Image = 0;

var View = 0;

var ScrollView = 0;

var FlatList = 0;

exports.Animation = Animation;
exports.Interpolation = Interpolation;
exports.Value = Value;
exports.ValueXY = ValueXY;
exports.$$event = $$event;
exports.delay = delay;
exports.sequence = sequence;
exports.parallel = parallel;
exports.stagger = stagger;
exports.loop = loop;
exports.createAnimatedComponent = createAnimatedComponent;
exports.timing = timing;
exports.spring = spring;
exports.decay = decay;
exports.stop = stop;
exports.start = start;
exports.reset = reset;
exports.Text = Text;
exports.Image = Image;
exports.View = View;
exports.ScrollView = ScrollView;
exports.FlatList = FlatList;
/* AnimatedRe-BsReactNativeWeb Not a pure module */
